### ISSUE TITLE
Use assertEqual from unittest instead of == in tests. 

### ISSUE THREAD

**Issue by mansimarkaur** [fizyk/pyramid_localize#33]
It's better to use the unittest module instead of going for assert and ==  while testing.

**Comment by fizyk** [comment]
I don't understand why.

I use pytest for all my tests, not unittest, and these asserts are kind of regular thing for pytest testing framework. Please see the first example on pytest page: http://docs.pytest.org/en/latest/

**Comment by gerva** [comment]
@fizyk sorry for the late answer, you're right let me look into this!
